# Generated by Django 4.1.4 on 2023-01-07 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('host_since', models.DateTimeField(null=True)),
                ('host_location', models.CharField(max_length=20, null=True)),
                ('host_response_time', models.FloatField(null=True)),
                ('host_response_rate', models.FloatField(null=True)),
                ('host_acceptance_rate', models.FloatField(null=True)),
                ('city', models.CharField(max_length=10, null=True)),
                ('distinct', models.CharField(max_length=20, null=True)),
                ('neighbor', models.CharField(max_length=20, null=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('host_identity_verified', models.BooleanField(null=True)),
                ('accommodates', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
                ('amenities', models.CharField(max_length=200, null=True)),
                ('minimum_nights', models.IntegerField(null=True)),
                ('maximum_nights', models.IntegerField(null=True)),
                ('review_scores_rating', models.IntegerField(null=True)),
                ('review_scores_accuracy', models.IntegerField(null=True)),
                ('review_scores_cleanliness', models.IntegerField(null=True)),
                ('review_scores_checkin', models.IntegerField(null=True)),
                ('review_scores_communication', models.IntegerField(null=True)),
                ('review_scores_location', models.IntegerField(null=True)),
                ('review_scores_value', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=15, null=True)),
                ('number_of_listings', models.IntegerField()),
                ('is_verified', models.BooleanField()),
                ('bedrooms', models.IntegerField()),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='utils.property')),
            ],
        ),
    ]
