# Generated by Django 4.1.4 on 2023-01-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='country',
        ),
        migrations.RemoveField(
            model_name='host',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='host',
            name='host_total_listings_count',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='instant_bookable',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='room_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_response_time',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
