# Generated by Django 4.1.4 on 2023-01-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host_info', '0002_remove_host_country_remove_host_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='number_of_listings',
        ),
    ]
