# Generated by Django 4.1.4 on 2023-01-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_info', '0003_remove_host_number_of_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
