# Generated by Django 4.1.4 on 2023-01-17 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host_info', '0005_alter_host_host_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='neighbor',
            new_name='neighborhood',
        ),
    ]
