# Generated by Django 4.1.4 on 2023-01-17 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host_info', '0006_rename_neighbor_host_neighborhood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='distinct',
            new_name='district',
        ),
    ]
