# Generated by Django 4.1.4 on 2023-01-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_info', '0007_rename_distinct_host_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='host_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='listing_id',
            field=models.IntegerField(null=True),
        ),
    ]
