# Generated by Django 4.1.4 on 2023-01-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_info', '0008_host_host_id_host_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_since',
            field=models.DateField(null=True),
        ),
    ]
