# Generated by Django 4.1.4 on 2023-01-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_info', '0009_alter_host_host_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='amenities',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
