# Generated by Django 4.1.4 on 2023-01-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_info', '0010_alter_host_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
