# Generated by Django 4.1.4 on 2023-01-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_info', '0011_alter_host_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
