# Generated by Django 4.1.4 on 2023-01-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_info', '0012_alter_host_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
