# Generated by Django 4.1.4 on 2023-01-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_info', '0013_alter_host_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='amenities',
            field=models.CharField(max_length=1544, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_location',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='neighborhood',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='room_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
