# Generated by Django 4.1.4 on 2023-04-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("host_info", "0015_hostrates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="host",
            name="property_type",
        ),
    ]
