# Generated by Django 4.1.4 on 2023-04-23 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0005_property_description"),
        ("host_info", "0016_remove_host_property_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="property_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="utils.property",
            ),
        ),
    ]
