# Generated by Django 4.1.4 on 2023-01-07 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel_search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('trip_place10_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='travel_search.tripplaces')),
                ('trip_place1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='travel_search.tripplaces')),
                ('trip_place2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='travel_search.tripplaces')),
                ('trip_place3_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='travel_search.tripplaces')),
                ('trip_place4_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='travel_search.tripplaces')),
                ('trip_place5_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='travel_search.tripplaces')),
                ('trip_place6_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='travel_search.tripplaces')),
                ('trip_place7_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='travel_search.tripplaces')),
                ('trip_place8_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='travel_search.tripplaces')),
                ('trip_place9_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='travel_search.tripplaces')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
