# Generated by Django 4.1.4 on 2023-06-11 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("host_info", "0017_host_property_type"),
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripplan",
            name="host_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="host_info.host",
            ),
        ),
    ]
