# Generated by Django 4.1.4 on 2023-06-12 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("travel_search", "0005_remove_tripplaces_place_type_id_and_more"),
        ("plans", "0002_tripplan_host_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tripplan",
            name="trip_place10_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="travel_search.tripplaces",
            ),
        ),
        migrations.AlterField(
            model_name="tripplan",
            name="trip_place1_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="travel_search.tripplaces",
            ),
        ),
        migrations.AlterField(
            model_name="tripplan",
            name="trip_place2_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="travel_search.tripplaces",
            ),
        ),
        migrations.AlterField(
            model_name="tripplan",
            name="trip_place3_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="travel_search.tripplaces",
            ),
        ),
        migrations.AlterField(
            model_name="tripplan",
            name="trip_place4_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="travel_search.tripplaces",
            ),
        ),
        migrations.AlterField(
            model_name="tripplan",
            name="trip_place5_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="travel_search.tripplaces",
            ),
        ),
        migrations.AlterField(
            model_name="tripplan",
            name="trip_place6_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="travel_search.tripplaces",
            ),
        ),
        migrations.AlterField(
            model_name="tripplan",
            name="trip_place7_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="travel_search.tripplaces",
            ),
        ),
        migrations.AlterField(
            model_name="tripplan",
            name="trip_place8_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="travel_search.tripplaces",
            ),
        ),
        migrations.AlterField(
            model_name="tripplan",
            name="trip_place9_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="travel_search.tripplaces",
            ),
        ),
        migrations.CreateModel(
            name="TipPlanRates",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rate_score", models.FloatField()),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="plans.tripplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
