# Generated by Django 4.1.4 on 2023-01-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('is_first_login', models.BooleanField(blank=True, default=True, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('distinct', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('neighbor', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('other_addr_infos', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('cellNo', models.CharField(blank=True, default=None, max_length=15, null=True)),
            ],
        ),
    ]
