# Generated by Django 4.1.4 on 2023-01-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='is_first_login',
        ),
    ]
