# Generated by Django 4.1.4 on 2023-01-08 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0003_remove_personalinfo_is_first_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='cellNo',
            new_name='cell_no',
        ),
    ]
