# Generated by Django 4.1.4 on 2023-01-07 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('rate_of_beach', models.FloatField()),
                ('rate_of_parks', models.FloatField()),
                ('rate_of_theaters', models.FloatField()),
                ('rate_of_mall', models.FloatField()),
                ('rate_of_museum', models.FloatField()),
                ('rate_of_zoo', models.FloatField()),
                ('rate_of_restaurant', models.FloatField()),
                ('rate_of_pubs', models.FloatField()),
                ('rate_of_art', models.FloatField()),
                ('rate_of_dance', models.FloatField()),
                ('rate_of_gym', models.FloatField()),
                ('rate_of_spa', models.FloatField()),
                ('rate_of_cafe', models.FloatField()),
                ('rate_of_viewpoints', models.FloatField()),
                ('rate_of_garden', models.FloatField()),
                ('rate_of_unknown', models.FloatField()),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('lead_time', models.IntegerField(default=0)),
                ('stays_in_weekend_nights', models.IntegerField(default=0)),
                ('stays_in_week_nights', models.IntegerField(default=0)),
                ('adults', models.IntegerField(default=0)),
                ('babies', models.IntegerField(default=0)),
                ('booking_changes', models.IntegerField(default=0)),
                ('days_in_waiting_list', models.IntegerField(default=0)),
                ('adr', models.IntegerField(default=0)),
                ('required_car_parking_spaces', models.IntegerField(default=0)),
                ('total_of_special_requests', models.IntegerField(default=0)),
                ('is_repeated_guest', models.CharField(default='', max_length=25)),
                ('customer_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='utils.customer')),
                ('deposit_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='utils.deposit')),
                ('distribution_channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='utils.marketdist')),
                ('market_segment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='utils.marketdist')),
                ('meal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='utils.meals')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccommodateSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('host_total_listing_account', models.IntegerField(null=True)),
                ('minimum_nights', models.IntegerField(null=True)),
                ('maximum_nights', models.IntegerField(null=True)),
                ('bedrooms', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('host_response_rate', models.FloatField(null=True)),
                ('host_acceptance_rate', models.FloatField(null=True)),
                ('property_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='utils.property')),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='utils.rooms')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
