# Generated by Django 4.1.4 on 2023-01-08 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_alter_amenities_label'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodatesurvey',
            name='amenities',
            field=models.ManyToManyField(to='utils.amenities'),
        ),
        migrations.AddField(
            model_name='personalsurvey',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='utils.hotels'),
        ),
    ]
