# Generated by Django 4.1.4 on 2023-04-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0002_accommodatesurvey_amenities_personalsurvey_hotel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accommodatesurvey",
            name="amenities",
        ),
    ]
