# Generated by Django 4.1.4 on 2023-04-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0004_amenities_description"),
        ("surveys", "0003_remove_accommodatesurvey_amenities"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accommodatesurvey",
            name="property_type",
        ),
        migrations.AddField(
            model_name="accommodatesurvey",
            name="amenities",
            field=models.ManyToManyField(to="utils.amenities"),
        ),
    ]
