# Generated by Django 4.1.4 on 2023-04-23 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0005_property_description"),
        ("surveys", "0004_remove_accommodatesurvey_property_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accommodatesurvey",
            name="room_type",
        ),
        migrations.AddField(
            model_name="accommodatesurvey",
            name="property_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="utils.property",
            ),
        ),
    ]
