# Generated by Django 4.1.4 on 2023-04-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0005_remove_accommodatesurvey_room_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalsurvey",
            name="customer_type",
        ),
        migrations.RemoveField(
            model_name="personalsurvey",
            name="deposit_type",
        ),
        migrations.RemoveField(
            model_name="personalsurvey",
            name="distribution_channel",
        ),
        migrations.RemoveField(
            model_name="personalsurvey",
            name="hotel",
        ),
        migrations.RemoveField(
            model_name="personalsurvey",
            name="market_segment",
        ),
        migrations.RemoveField(
            model_name="personalsurvey",
            name="meal",
        ),
    ]
