# Generated by Django 4.1.4 on 2023-06-15 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0008_remove_tripsurvey_rate_of_unknown"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accommodatesurvey",
            name="price",
        ),
    ]
