# Generated by Django 4.1.4 on 2023-06-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0009_remove_accommodatesurvey_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodatesurvey",
            name="price",
            field=models.IntegerField(null=True),
        ),
    ]
