# Generated by Django 4.1.4 on 2023-06-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0010_accommodatesurvey_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalsurvey",
            name="children",
            field=models.IntegerField(default=0),
        ),
    ]
