# Generated by Django 4.1.4 on 2023-06-15 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0011_personalsurvey_children"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalsurvey",
            name="is_repeated_guest",
        ),
    ]
