# Generated by Django 4.1.4 on 2023-06-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0012_remove_personalsurvey_is_repeated_guest"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalsurvey",
            name="is_repeated_guest",
            field=models.IntegerField(default=0),
        ),
    ]
