# Generated by Django 4.1.4 on 2023-06-15 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0013_personalsurvey_is_repeated_guest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalsurvey",
            name="distribution_channel",
        ),
        migrations.RemoveField(
            model_name="personalsurvey",
            name="market_segment",
        ),
    ]
