# Generated by Django 4.1.4 on 2023-06-15 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0009_delete_marketdist"),
        ("surveys", "0014_remove_personalsurvey_distribution_channel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalsurvey",
            name="distribution_channel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="utils.distribution",
            ),
        ),
        migrations.AddField(
            model_name="personalsurvey",
            name="market_segment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="utils.market",
            ),
        ),
    ]
