# Generated by Django 4.1.4 on 2023-06-15 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0015_personalsurvey_distribution_channel_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accommodatesurvey",
            old_name="host_total_listing_account",
            new_name="host_total_listing_count",
        ),
    ]
