# Generated by Django 4.1.4 on 2023-06-15 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "surveys",
            "0016_rename_host_total_listing_account_accommodatesurvey_host_total_listing_count",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="accommodatesurvey",
            old_name="host_total_listing_count",
            new_name="host_total_listings_count",
        ),
    ]
