# Generated by Django 4.1.4 on 2023-06-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "surveys",
            "0017_rename_host_total_listing_count_accommodatesurvey_host_total_listings_count",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="tripsurvey",
            old_name="rate_of_art",
            new_name="rate_of_art_gallery",
        ),
        migrations.RenameField(
            model_name="tripsurvey",
            old_name="rate_of_beach",
            new_name="rate_of_religious_place",
        ),
        migrations.RemoveField(
            model_name="tripsurvey",
            name="rate_of_dance",
        ),
        migrations.RemoveField(
            model_name="tripsurvey",
            name="rate_of_garden",
        ),
        migrations.AddField(
            model_name="tripsurvey",
            name="rate_of_monument",
            field=models.FloatField(null=True),
        ),
    ]
