# Generated by Django 4.1.4 on 2023-01-07 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=10)),
                ('lable', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TripPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('place_name', models.CharField(max_length=20)),
                ('google_maps_url', models.URLField()),
                ('longitude', models.FloatField()),
                ('lattitude', models.FloatField()),
                ('place_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='travel_search.place')),
            ],
        ),
    ]
