# Generated by Django 4.1.4 on 2023-01-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='lable',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='tripplaces',
            old_name='lattitude',
            new_name='latitude',
        ),
    ]
