# Generated by Django 4.1.4 on 2023-01-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_search', '0003_tripplaces_google_maps_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
