# Generated by Django 4.1.4 on 2023-01-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_search', '0004_alter_place_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripplaces',
            name='place_type_id',
        ),
        migrations.AddField(
            model_name='tripplaces',
            name='place_type_id',
            field=models.ManyToManyField(to='travel_search.place'),
        ),
    ]
