# Generated by Django 4.1.4 on 2023-01-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='label',
            field=models.CharField(max_length=40),
        ),
    ]
