# Generated by Django 4.1.4 on 2023-04-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0003_alter_amenities_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="amenities",
            name="description",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
