# Generated by Django 4.1.4 on 2023-04-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0004_amenities_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="description",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
