# Generated by Django 4.1.4 on 2023-04-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0005_property_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="description",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="deposit",
            name="description",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="hotels",
            name="description",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="marketdist",
            name="description",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="meals",
            name="description",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="rooms",
            name="description",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
