# Generated by Django 4.1.4 on 2023-04-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0006_customer_description_deposit_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="description",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="description",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="hotels",
            name="description",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="marketdist",
            name="description",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="meals",
            name="description",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="description",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
