# Generated by Django 4.1.4 on 2023-06-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0007_alter_customer_description_alter_deposit_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Distribution",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("type", models.IntegerField()),
                ("label", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("type", models.IntegerField()),
                ("label", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
