# Generated by Django 4.1.4 on 2023-06-15 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0008_distribution_market"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MarketDist",
        ),
    ]
